language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '9'
before_install:
  - yarn global add now
before_script:
  - yarn validate
  - yarn clean
script: yarn rollup:build:prod
after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/now.sh
  on:
    branch: master
