language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
install:
  - yarn global add codecov
  - yarn install
script:
  - yarn validate
  - codecov

jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn build
          - yarn semantic-release
        on:
          branch: master
