language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '9'
env:
  - NODE_ENV=production
before_install:
  - npm install -g now
before_script:
  - npm run validate
  - npm run clean
script: npm run rollup:build
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/now.sh
  on:
    branch: master
